### ISSUE TITLE
vanilla team messages are blank - v210.6.5.1 - 1.21

### ISSUE THREAD

**Issue by xxtg666** [mrbuilder1961/WheresMyChatHistory#199]
### Description
When `Chat Patches` and `No Chat Reports` are installed together, the team messages received are blank and errors are reported in the logs

### How to reproduce
Send a team message via `/teammsg`

### Expected result
Display the team messages

### Log file link
```
[13:36:09] [Render thread/ERROR]: [ChatUtils.modifyMessage] An error occurred while modifying message '-> [1] <xxtg666> test', returning original:
[13:36:09] [Render thread/ERROR]: [ChatUtils.modifyMessage] /!\ Please report this error on GitHub or Discord with the full log file attached! /!\
java.lang.UnsupportedOperationException: null
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147) ~[?:?]
	at net.minecraft.class_5250.method_10852(class_5250.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_5250.method_27693(class_5250.java:56) ~[client-intermediary.jar:?]
	at obro1961.chatpatches.util.ChatUtils.modifyMessage(ChatUtils.java:202) ~[chatpatches-210.6.5.1.jar:?]
	at net.minecraft.class_338.localvar$zzc000$chatpatches$modifyMessage(class_338.java:716) ~[client-intermediary.jar:?]
	at net.minecraft.class_338.method_44811(class_338.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_338.method_1812(class_338.java:208) ~[client-intermediary.jar:?]
	at net.minecraft.class_7594.method_44736(class_7594.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_43596(class_634.java:904) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_43631(class_7439.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_11054(class_7439.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) [JavaWrapper.jar:?]
[13:36:09] [Render thread/INFO]: [CHAT] [13:36:09] 
```

### Specs and Details
- Computer OS
> Windows 11
- Mod version
> v210.6.5.1
- Fabric, Fabric API, and YetAnotherConfigLib versions
> Fabric 0.16.2, Fabric API 0.102.0+1.21, YetAnotherConfigLib 3.5.0+1.21-fabric
- Mod Menu / Catalogue and Menulogue versions (if installed)
> no

Optional but suggested information:
- `chatpatches.json` file (if pasted use the format: \`\`\`json\n\<config data>\n\`\`\`)
- `chatlog.json` file (DO NOT PASTE, put a link using a site like https://pastebin.com)
> I didn't change the default configuration file

### Additional context
Installing either `Chat Patches` or `No Chat Reports` separately will not cause problems, but installing both together will cause problems.
No Chat Reports version: 1.21-v2.8.0

**Comment by mrbuilder1961** [comment]
is this on a server or singleplayer? and is nochatreports configured to change chat messages to system messages?

**Comment by xxtg666** [comment]
Both servers and singleplayer have this problem, and nochatreports is configured as `"convertToGameMessage": true`

**Comment by mrbuilder1961** [comment]
could you please send the full log file with https://mclo.gs?

**Comment by xxtg666** [comment]
ok
https://mclo.gs/Mf1olJH

**Comment by mrbuilder1961** [comment]
thanks for the log!! i'd also appreciate if you could try jar artifact from the latest build here, instructions on how to use it are available in the README#help section: ~~https://github.com/mrbuilder1961/ChatPatches/actions/runs/10731835757~~ https://github.com/mrbuilder1961/ChatPatches/actions/runs/10761047033

**Comment by mrbuilder1961** [comment]
sorry it automatically closed it 🙄 but i'm hoping the celebratory reaction meant it is working? i still need a concrete confirmation but im hoping all is well!

**Comment by xxtg666** [comment]
it is working!
